/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package crip_p2;

import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Interfaz extends javax.swing.JFrame {
    int contadorFicheros = 1;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JTabbedPane();
        periodicidad = new javax.swing.JPanel();
        titulo1Periodicidad = new javax.swing.JLabel();
        titulo2Periodicidad = new javax.swing.JLabel();
        sucesionPeriodicidad = new javax.swing.JTextField();
        aceptarPeriodicidad = new javax.swing.JButton();
        comentarioPeriodicidad = new javax.swing.JLabel();
        lfsr = new javax.swing.JPanel();
        tituloLFSR = new javax.swing.JLabel();
        comentario1PolinomioLFSR = new javax.swing.JLabel();
        comentario2LPolinomioFSR = new javax.swing.JLabel();
        polinomioLFSR = new javax.swing.JTextField();
        cometarioSucesionLFSR = new javax.swing.JLabel();
        sucesionLFSR = new javax.swing.JTextField();
        comentarioSolucionLFSR = new javax.swing.JLabel();
        solucionLFSR = new javax.swing.JTextField();
        aceptarLFSR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo1Periodicidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo1Periodicidad.setText("Periodicidad de una");

        titulo2Periodicidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo2Periodicidad.setText("sucesión de bits");

        aceptarPeriodicidad.setText("Aceptar");
        aceptarPeriodicidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarPeriodicidadActionPerformed(evt);
            }
        });

        comentarioPeriodicidad.setText("Introduzca la secuencia de 1s y 0s:");

        javax.swing.GroupLayout periodicidadLayout = new javax.swing.GroupLayout(periodicidad);
        periodicidad.setLayout(periodicidadLayout);
        periodicidadLayout.setHorizontalGroup(
            periodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periodicidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(periodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periodicidadLayout.createSequentialGroup()
                        .addGroup(periodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo1Periodicidad)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periodicidadLayout.createSequentialGroup()
                                .addComponent(titulo2Periodicidad)
                                .addGap(18, 18, 18)))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, periodicidadLayout.createSequentialGroup()
                        .addComponent(aceptarPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
            .addGroup(periodicidadLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(periodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comentarioPeriodicidad)
                    .addComponent(sucesionPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );
        periodicidadLayout.setVerticalGroup(
            periodicidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(periodicidadLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titulo1Periodicidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo2Periodicidad)
                .addGap(31, 31, 31)
                .addComponent(comentarioPeriodicidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucesionPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(aceptarPeriodicidad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        panel.addTab("Periodicidad", periodicidad);

        tituloLFSR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloLFSR.setText("LFSR");

        comentario1PolinomioLFSR.setText("Introduce los grados del polinomio separados por comas:");

        comentario2LPolinomioFSR.setText("(Ej. 5,4,3 para el polinomio D^5+D^4+D^3+1)");

        polinomioLFSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polinomioLFSRActionPerformed(evt);
            }
        });

        cometarioSucesionLFSR.setText("Introduce la sucesion de 0s y 1s:");

        comentarioSolucionLFSR.setText("La solucion es:");

        solucionLFSR.setEditable(false);

        aceptarLFSR.setText("Aceptar");
        aceptarLFSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarLFSRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lfsrLayout = new javax.swing.GroupLayout(lfsr);
        lfsr.setLayout(lfsrLayout);
        lfsrLayout.setHorizontalGroup(
            lfsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfsrLayout.createSequentialGroup()
                .addGroup(lfsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lfsrLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(lfsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comentarioSolucionLFSR)
                            .addComponent(solucionLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lfsrLayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(tituloLFSR))
                            .addGroup(lfsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comentario2LPolinomioFSR)
                                .addComponent(comentario1PolinomioLFSR)
                                .addComponent(polinomioLFSR)
                                .addComponent(cometarioSucesionLFSR)
                                .addComponent(sucesionLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lfsrLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(aceptarLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        lfsrLayout.setVerticalGroup(
            lfsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lfsrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLFSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comentario1PolinomioLFSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comentario2LPolinomioFSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(polinomioLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cometarioSucesionLFSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sucesionLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comentarioSolucionLFSR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solucionLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aceptarLFSR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panel.addTab("LFSR", lfsr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarPeriodicidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarPeriodicidadActionPerformed
        String sucesion = sucesionPeriodicidad.getText();
        if (sucesion.matches("[01]+")) {
            Integer longitud = Funciones.comprobarPeriocidad(sucesion);
            if (longitud == null) {
                JOptionPane.showMessageDialog(null, "No es una sucesion periodica",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Es una sucesión periodica de periodo " + longitud,
                        "Error", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No es una sucesion de 0s y 1s",
                        "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarPeriodicidadActionPerformed

    private void polinomioLFSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polinomioLFSRActionPerformed
        
    }//GEN-LAST:event_polinomioLFSRActionPerformed

    private void aceptarLFSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarLFSRActionPerformed
        String polinomio = polinomioLFSR.getText();
        String sucesion = sucesionLFSR.getText();
        if (!polinomio.matches("[0-9]+(,[0-9]+)*")){
            JOptionPane.showMessageDialog(null, "No es un polinomio valido",
                        "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!sucesion.matches("[01]+")) {
            JOptionPane.showMessageDialog(null, "No es una sucesion de 0s y 1s",
                        "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String sucesionPseudoAleatoria = Funciones.lfsr(polinomio, sucesion);
            solucionLFSR.setText(sucesionPseudoAleatoria);
            FileWriter fichero = null;
            PrintWriter pw;
            try {
                fichero = new FileWriter("lfsr" + contadorFicheros + ".txt");
                pw = new PrintWriter(fichero);
                pw.println(sucesionPseudoAleatoria);
                contadorFicheros++;
                JOptionPane.showMessageDialog(null, "Fichero guardado en: " + System.getProperty("user.dir"),
                        "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se ha podido guardar el fichero: " +e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    fichero.close();
                } catch (Exception e2) {
                    JOptionPane.showMessageDialog(null, "No se ha podido cerrar el fichero: " + e2.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_aceptarLFSRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarLFSR;
    private javax.swing.JButton aceptarPeriodicidad;
    private javax.swing.JLabel comentario1PolinomioLFSR;
    private javax.swing.JLabel comentario2LPolinomioFSR;
    private javax.swing.JLabel comentarioPeriodicidad;
    private javax.swing.JLabel comentarioSolucionLFSR;
    private javax.swing.JLabel cometarioSucesionLFSR;
    private javax.swing.JPanel lfsr;
    private javax.swing.JTabbedPane panel;
    private javax.swing.JPanel periodicidad;
    private javax.swing.JTextField polinomioLFSR;
    private javax.swing.JTextField solucionLFSR;
    private javax.swing.JTextField sucesionLFSR;
    private javax.swing.JTextField sucesionPeriodicidad;
    private javax.swing.JLabel titulo1Periodicidad;
    private javax.swing.JLabel titulo2Periodicidad;
    private javax.swing.JLabel tituloLFSR;
    // End of variables declaration//GEN-END:variables
}
